### ISSUE TITLE
A typo and a suggestion

### ISSUE THREAD

**Issue by CodeSadhu** [vanigupta20024/vanigupta20024.github.io#1]
## [Intro](https://vanigupta20024.github.io/#intro)
* Paragraph 2, line 2: 
"I **oftenly** get stuck **with** challenging doubts **which** helps me..." --> "I **often** get stuck **on** challenging doubts **that** help me..."

## [Contact](https://vanigupta20024.github.io/#contact)
* Instead of a form you could just share your contact details (email/phone numbers). Would be more convenient for you.

**Comment by vanigupta20024** [comment]
Thanks @CodeSadhu I've corrected the typos. Will change the form later!

**Comment by CodeSadhu** [comment]
@vanigupta20024 No problem! Keep rolling!
